# Generated by Django 4.2 on 2023-05-02 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_created_at_user_firs_name_user_is_employe_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="firs_name",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
    ]
