# Generated by Django 4.2 on 2023-05-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
        ("follows", "0002_alter_follow_user"),
        ("users", "0005_alter_user_created_at_alter_user_is_employe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follow",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users",
                to="follows.follow",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="followed",
            field=models.ManyToManyField(
                related_name="followed", through="follows.Follow", to="books.book"
            ),
        ),
    ]
