# Generated by Django 4.2 on 2023-05-04 21:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_user_follow_user_followed"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="follow",
        ),
    ]
