# Generated by Django 4.2 on 2023-05-08 13:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
        ("lending", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="lent_user",
            field=models.ManyToManyField(
                related_name="lent_copy",
                through="lending.Lending",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
