# Generated by Django 4.2 on 2023-05-05 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0003_alter_lending_devolution_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_alter_copy_book_alter_copy_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="copy",
            name="lent_user",
            field=models.ManyToManyField(
                related_name="lent_copy",
                through="lending.Lending",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
