# Generated by Django 4.2 on 2023-05-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_copy_book_alter_copy_is_available"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="copias",
            field=models.IntegerField(default=0),
        ),
    ]
