# Generated by Django 4.2 on 2023-05-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0003_book_copias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="copy",
            name="is_available",
            field=models.BooleanField(default=True, null=True),
        ),
    ]
