# Generated by Django 4.2 on 2023-05-05 17:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_copy_is_available"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="copias",
            new_name="copy",
        ),
    ]
