# Generated by Django 4.2 on 2023-05-10 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lending",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "devolution_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023,
                            5,
                            13,
                            14,
                            37,
                            46,
                            607709,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="copy_lending",
                        to="books.copy",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
