# Generated by Django 4.2 on 2023-05-04 21:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="devolution_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 6, 21, 50, 58, 969527, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
