# Generated by Django 4.2 on 2023-05-08 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lending",
            old_name="copy_id",
            new_name="copy",
        ),
        migrations.RenameField(
            model_name="lending",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="lending",
            name="devolution_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 14, 42, 33, 581016, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
