# Generated by Django 4.2 on 2023-05-08 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="devolution_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 10, 13, 50, 55, 402710, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
