# Generated by Django 4.2 on 2023-05-09 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0003_rename_copy_id_lending_copy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="devolution_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 9, 19, 6, 3, 899693, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
