# Generated by Django 4.2 on 2023-05-05 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lending", "0003_alter_lending_devolution_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lending",
            name="devolution_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 5, 7, 16, 11, 49, 89636, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
